name: Sync Live Theme Changes

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    name: Sync Live Theme
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Sync live theme changes
      - name: Sync from live theme
        id: sync
        uses: ShopLab-Team/shopify-theme-deployment-manager@v1
        with:
          mode: sync-live
          # Provide store URL via input
          store: ${{ secrets.SHOPIFY_STORE_URL }}
          
          # Create PR instead of direct push (recommended)
          sync_type: pr
          
          # Optional: customize branch names (defaults shown)
          # sync_branch: remote_changes      # Branch to commit changes to
          # sync_target_branch: staging      # Target branch for PR
          
          # Optional: customize what to sync (defaults to JSON files)
          # sync_only_globs: |
          #   templates/*.json
          #   config/settings_data.json
          #   locales/*.json
        
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      # Optional: Display sync results
      - name: Sync Summary
        if: always()
        run: |
          echo "### 📊 Sync Results"
          echo "- **Status**: ${{ steps.sync.outcome }}"
          echo "- **Changes**: ${{ steps.sync.outputs.changes || 'None' }}"
          echo "- **PR**: ${{ steps.sync.outputs.pull_request_url || 'N/A' }}"
