name: Sync Live JSON → Repo

on:
  schedule:
    # Runs every 5 minutes (best effort, minimum GitHub Actions interval)
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        default: false
        type: boolean
      output_mode:
        description: 'Output mode'
        required: false
        default: 'pr'
        type: choice
        options:
          - pr
          - push

jobs:
  sync:
    name: Sync Live Theme Changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Sync live JSON to repository
        id: sync
        uses: ./
        with:
          mode: sync-live
          store: ${{ vars.SHOPIFY_STORE }}
          sync_only_globs: |
            templates/*.json
            locales/*.json
            config/settings_data.json
          sync_branch: remote_changes
          sync_commit_message: 'chore(sync): import live JSON changes'
          sync_output: ${{ github.event.inputs.output_mode || 'pr' }}
          dry_run: ${{ github.event.inputs.dry_run }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create sync report issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Live Sync Failed - ${new Date().toISOString()}`;
            const body = `## Live Theme Sync Failed
            
            The scheduled sync from the live theme failed at ${new Date().toISOString()}.
            
            **Workflow Run**: [View logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            
            Please investigate and run manually if needed.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['sync-failure', 'automated']
            });

